# Generated by Django 3.2 on 2021-05-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessoriesCategoryModel',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('hsn', models.CharField(max_length=30)),
                ('gst', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DesignerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('dph_no', models.CharField(max_length=10)),
                ('daddress', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='productCategoryModel',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('hsn', models.CharField(max_length=30)),
                ('gst', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dealersPrice', models.FloatField()),
                ('mrp', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.productcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('mname', models.CharField(blank=True, max_length=30, null=True)),
                ('lname', models.CharField(blank=True, max_length=30, null=True)),
                ('ph_no', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('walk_in_date', models.DateField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('Retail Customer', 'Retail Customer'), ('Full Kitchen Customer', 'Full Kitchen Customer')], max_length=100, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('measure_date', models.DateField(blank=True, null=True)),
                ('login_date', models.DateField(blank=True, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('designer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.designermodel')),
            ],
        ),
        migrations.CreateModel(
            name='accessoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('dealersPrice', models.FloatField()),
                ('mrp', models.FloatField()),
                ('stdPack', models.IntegerField()),
                ('dimensions', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.accessoriescategorymodel')),
            ],
        ),
    ]
