# Generated by Django 3.2 on 2021-05-29 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanjivini_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.invoicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.accessoriesmodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.customermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='order_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.ordermodel'),
        ),
        migrations.CreateModel(
            name='InstallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode_of_pay', models.CharField(max_length=50)),
                ('chequeno', models.CharField(max_length=30)),
                ('amount_paid', models.FloatField()),
                ('payid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.paymentmodel')),
            ],
        ),
    ]
