# Generated by Django 3.2 on 2021-06-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanjivini_home', '0003_auto_20210601_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmodel',
            name='payid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.ordermodel'),
        ),
    ]
