# Generated by Django 3.2 on 2021-06-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanjivini_home', '0004_alter_installmodel_payid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.accessoriesmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.productmodel'),
        ),
    ]
