# Generated by Django 3.2 on 2021-06-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanjivini_home', '0005_auto_20210601_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='designer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanjivini_home.designermodel'),
        ),
    ]
